site:
  url: 'http://localhost/addon-static-pages/demo/'

addons:
  activate:
    - static-pages
    - php-content

theme:
  activate:
    - core/basic

templates:
  site:
    name: Static pages demo
