# The following config is available with this addon
addons:
  config:
    leafcutter/addon-static-pages:
      # The number of seconds after which a page is considered
      # stale and will be regenerated. The actual time between
      # page regenerations may be longer, depending on your output
      # or content cache lifetimes.
      ttl: 5
      # If you're removing static pages on a live site, you should
      # run with the addon installed, but disabled via this config
      # option, until all html files are removed.
      # On a large or less busy site it is more adviseable to 
      # redeploy, or manually remove the generated HTML files
      # somehow.
      enabled: true
